version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    depends_on:
      - db
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  db:
    image: sqlite:latest
    volumes:
      - ./db.sqlite3:/db.sqlite3






